### ISSUE TITLE
use case: train network on remote machine using Exodus, deploy trained network on chip on local machine without GPU

### ISSUE THREAD

**Issue by biphasic** [synsense/sinabs#14]
we should make sure that this workflow is supported

**Comment by biphasic** [comment]
currently this throws:
> raise RuntimeError(‘Error(s) in loading state_dict for {}:\n\t{}’.format(
RuntimeError: Error(s) in loading state_dict for Sequential:
        Unexpected key(s) in state_dict: “1.activations”, “4.activations”, “8.activations”, “12.activations”.

**Comment by bauerfe** [comment]
When calling the `load_state_dict` method, you can just set `strict=False` , then you should not get this error.

However, the deeper reason for this is that the Exodus layers have `activations` registered as buffers, whereas the standard sinabs layers don't. I think we should implement the same behavior for both.

Including the activations in the buffers ensures through the `is_state_initialized` and `state_has_shape` methods that the activations are initialized with correct shape.

**Comment by biphasic** [comment]
I recently ran into this error myself and I think with `strict=False` it's actually alright. Sinabs just doesn't need to make use of an additional `activation` state which costs additional memory. Although we could of course adapt it for the sake of it. My issue is more that it's not documented somewhere.

**Comment by sheiksadique** [comment]
This could be included in the How-to section of the documentation.

Should be resolved by consistent API/naming convention.

**Comment by bauerfe** [comment]
The additional `activation` state has been removed from exodus and unit tests have been introduced to ensure that state dicts can be transferred between both backends without any issues.

**Comment by biphasic** [comment]
amazing
