### ISSUE TITLE
make synops loss work again and write tutorial notebook

### ISSUE THREAD

**Issue by biphasic** [synsense/sinabs#15]

**Comment by biphasic** [comment]
wrote a first version of a tutorial notebook https://github.com/synsense/sinabs/blob/develop/docs/tutorials/synops_loss.ipynb

**Comment by biphasic** [comment]
this works now https://github.com/synsense/sinabs/commit/46561f6a762aaa9b7758b5ec1a758394464d2a8a
I also updated the tutorial notebook.
Turns out that this was broken already before I started working on Sinabs.

**Comment by biphasic** [comment]
@sheiksadique this is done. The tutorial is quite minimal at the moment, should I extend to fully fledged training loop? https://github.com/synsense/sinabs/blob/develop/docs/tutorials/synops_loss.ipynb

**Comment by sheiksadique** [comment]
done
