### ISSUE TITLE
spike_fn, reset_fn and surrogate_grad_fn as layer parameters

### ISSUE THREAD

**Issue by bauerfe** [synsense/sinabs#17]
For spiking layers the spike and reset behaviors as well as surrogate gradients are currently defined by passing an `ActivationFunction` object at instantiation.

This has two disadavantages:
1. First having to instantiate an ActivationFunction is a bit tedious
2. The default behavior is not clear this way.

Passing the spike_fn, reset_fn and surrogate_grad_fn directly as layer parameters rather than an ActivationFunction would solve these problems. The ActivationFunction could then be instantiated inside the forward functionals.

**Comment by biphasic** [comment]
done in 12754809f54b308f7ae17ad99a2fcfffb297c994
