### ISSUE TITLE
More sensible change log

### ISSUE THREAD

**Issue by bauerfe** [synsense/sinabs#223]
Currently the change log is auto-generated from commit messages.  As a changelog it is not very helpful, because these messages are often not explanatory enough. Furthermore, it often causes confusion when commiting, because it gets updated after the commit, hence requiring a separate commit for the updated changelog.

I suggest to add to the changelog manually, each time a branch gets merged. This means the reviewer will have the responsibility to ensure this happens. However, it will hopefully result in a much more helpful changelog.

What do you think @sheiksadique @ssinhaleite ?

**Comment by sheiksadique** [comment]
Yes I completely agree with you. I run into the same issues with this autogenerated change log.

**Comment by ssinhaleite** [comment]
Yes, I totally agree. Adding a line to the changelog can be seen as part of our "definition of done."
It is easy to add a default checklist in a merge request that asks the reviewer to verify the changelog was updated.

**Comment by bauerfe** [comment]
Glad that we all agree :) 
@ssinhaleite I think the checklist is a good idea, as long as it's not too exhaustive. would you mind adding one?
