### ISSUE TITLE
Deploy version 2.0 of the documentation to read-the-docs

### ISSUE THREAD

**Issue by bauerfe** [synsense/sinabs#233]
Somehow the docs did not get deployed automatically with the release of Sinabs 2.0. Under www.sinabs.ai the highest version is still 1.2

**Comment by ssinhaleite** [comment]
I have noticed that there is no action to publish the documentation. I will have a look later if we removed it from the pipeline to recover it, and even if not, I will update the YAML

**Comment by bauerfe** [comment]
This has been fixed.
