### ISSUE TITLE
Documentation can not be built with Python >= 3.10

### ISSUE THREAD

**Issue by ssinhaleite** [synsense/sinabs#243]
We are using `zoneinfo`, which provides minimum support for Python 3.9 and above.

We need to change the way it is used, see:
https://pypi.org/project/backports.zoneinfo/

**Comment by bauerfe** [comment]
Do you know where (and why) we are using this? I can't find it anywhere in the repo.

**Comment by ssinhaleite** [comment]
This happened when I tried to generate docs in a system with Python 3.12.
I didn't write it down from where it came from...
I remember I had to downgrade my Python to compile the docs.

I can have a look at this again tomorrow.

**Comment by bauerfe** [comment]
Currently does not seem to be an issue anymore.
