### ISSUE TITLE
Change the way to calculate Synops per second. Make it support batch calculation.

### ISSUE THREAD

**Issue by Allan-Yoriichi** [synsense/sinabs#29]
### Description
The current Synop calculation doesn't support the batch_size > 1 case. Which limits the training speed if want to use SynOp Loss during training.

```
def synops_hook(layer, inp, out):
    assert len(inp) == 1, "Multiple inputs not supported for synops hook"
    inp = inp[0]
    layer.tot_in = inp.sum().item()
    layer.tot_out = out.sum().item()
    layer.synops = layer.tot_in * layer.fanout
    layer.tw = inp.shape[0]
```
### Solution
Make the synops_hook calculate the averge Synops of one batch of data.

**Comment by biphasic** [comment]
it actually does calculate it for all batches. inp is a tuple of inputs, hence the inp=inp[0].

**Comment by Allan-Yoriichi** [comment]
> it actually does calculate it for all batches. inp is a tuple of inputs, hence the inp=inp[0]. 

If so, the tw is not just the time-window right? It would be batch*time_steps

**Comment by biphasic** [comment]
you're right, this doesn't make sense. But I think it should be shape[1]. why include the batch size?

**Comment by Allan-Yoriichi** [comment]
> you're right, this doesn't make sense. But I think it should be shape[1]. why include the batch size?

Because the Conv2d layer only take a inp tensor with 4 dims,[batch, channel, H, W]. But the spike train will shave shape [batch, time-step, channel, H, W] and we reshape it to [batch*time-step, channel, H, W] if use IAFSqueeze

**Comment by Allan-Yoriichi** [comment]
Sorry I misunderstood the SynOps/s calculation. It's correct and I'm going to close this issue.
