### ISSUE TITLE
IAF layer is not expected to have any parameters. But tau_mem is listed as a parameter of this layer.

### ISSUE THREAD

**Issue by sheiksadique** [synsense/sinabs#30]

**Comment by sheiksadique** [comment]
It seems like this is a side effect of `IAF` inheriting from `LIF`.
This seems like an unnecessary complication.

It also seems like this would increase the computational cost for `IAF` forward pass.
It would be useful to do some profiling/speed tests.

**Comment by biphasic** [comment]
agreed, tau_mem is essentially infinite in IAF so as to re-use a maximum of the LIF implementation. You're right that tau_mem shouldn't be a parameter. I will look into how this can be prevented

**Comment by sheiksadique** [comment]
I have a branch where I re-implemented the neuron to not have dependence on LIF. (Sort of going back).
Will have to run some bench marks on performance/speed.

**Comment by biphasic** [comment]
great stuff. Happy to run this on the MNIST baseline benchmark I implemented the other day

**Comment by sheiksadique** [comment]
Fixed with PR #34
