### ISSUE TITLE
MultiGausian incorrect.

### ISSUE THREAD

**Issue by sheiksadique** [synsense/sinabs#54]
The multigausian surrogate gradient function seems to be in fact a single spike Gaussian and not applicable to multi-spike like is the case for MultiExponential

**Comment by biphasic** [comment]
The Multi-Gaussian is taken from the [paper](https://www.biorxiv.org/content/10.1101/2021.03.22.436372v2) and is a weighted sum of multiple Gaussians. What you are referring to is the periodic version of surrogate gradient functions such as [PeriodicExponential](https://sinabs.readthedocs.io/en/v1.0.3/api/generated/sinabs.activation.PeriodicExponential.html). It's true that we might need a PeriodicMultiGaussian to see how it performs.

**Comment by sheiksadique** [comment]
Aha that makes sense! Thanks for the clarification. Alright, I will raise another issues/feature request for a Periodic version of the Gaussian.

**Comment by biphasic** [comment]
Turns out the MultiGaussian was just a single Gaussian. This is fixed in 0070a9010bf659051d5276cdb35a0a90639e9907
