### ISSUE TITLE
Github doesn't recognise the tag based releases

### ISSUE THREAD

**Issue by sheiksadique** [synsense/sinabs#63]
The latest (and the only) release shown on GitHub page is 1.0.1 even when a lot of newer versions have been released. We should be able to automate the GitHub release process based on the following link.

https://github.com/marketplace/actions/github-create-tag-release

**Comment by biphasic** [comment]
Nice I like this idea!

**Comment by biphasic** [comment]
works now :) bf49a8d97dbbe40035d71201caf3879fe7a7f54d
