### ISSUE TITLE
SNNAnalyzer: Synops are summed over samples in batch rather than averaged

### ISSUE THREAD

**Issue by bauerfe** [synsense/sinabs#89]
When calling `SNNAnalyzer.get_layer_statistics` with `average=True`, it will take the average over all accumulated synops counts. This average is also across the samples withing a single batch, such that the end result does not increase with the batch size of the data.

When calling the method with `average=False` (the default), statistics are retrieved only for the last batch. Now synops counts are summed over samples, such that for larger batches the returned value increases, even if the underlying spiking dynamics are the same. This behavior is unexpected.

The corresponding unit test, `tests.test_synops_counter.test_linear_synops_counter_across_batches`, only tests for batch size 1, where it makes no difference.

**Comment by biphasic** [comment]
good catch @bauerfe
