### ISSUE TITLE
Wrong implementation of periodic surrogate gradient 

### ISSUE THREAD

**Issue by ccaccavella** [synsense/sinabs#97]
The periodic exponential surrogate gradient (https://github.com/synsense/sinabs/blob/develop/sinabs/activation/surrogate_gradient_fn.py#L104) does not have the expected behavior when the membrane potential threshold is different then 1.0. Specifically the peaks of the function are not always 1.0 and the function has a decaying trend.

**Comment by bauerfe** [comment]
Thanks again for pointing this out! 
I openend a PR to fix this issue.
